# Generated by Django 5.2.6 on 2025-11-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X-Large', 'XL')], max_length=10),
        ),
    ]
