# Generated by Django 5.2.6 on 2025-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_basket_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='promo_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
